[package]
name = "uselesskey-bdd"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dev-dependencies]
cucumber.workspace = true
tokio.workspace = true
rsa.workspace = true
ed25519-dalek.workspace = true
p256 = { version = "0.13", features = ["ecdsa", "pkcs8", "pem"] }
p384 = { version = "0.13", features = ["ecdsa", "pkcs8", "pem"] }
x509-parser = "0.16"
serde_json.workspace = true
uselesskey = { path = "../uselesskey", features = ["jwk", "ed25519", "ecdsa", "x509", "hmac"] }
uselesskey-core = { path = "../uselesskey-core" } # for TempArtifact

[[test]]
name = "bdd"
harness = false
