[package]
name = "uselesskey-x509"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "X.509 certificate fixtures for testing"
categories = ["development-tools::testing"]
keywords = ["x509", "fixtures", "testing"]
readme = "../../README.md"
authors.workspace = true

[dependencies]
uselesskey-core = { path = "../uselesskey-core", version = "0.1.0" }
uselesskey-rsa = { path = "../uselesskey-rsa", version = "0.1.0" }
rcgen = "0.13"
rustls-pki-types = "1"
x509-parser = "0.16"
time = "0.3"
blake3.workspace = true
rand_core.workspace = true

[dev-dependencies]
proptest.workspace = true
rstest.workspace = true
rand_chacha.workspace = true
